jenkins-infra/docker-jenkins-weeklyci

- plugins.txt
The ssh agent is failing for the windows job.
As suggested by @daniel-beck, the latest ssh-agent version introduced a breaking change should use version 1.21 until we improve the ssh command from the windows container
https://updates.jenkins.io/download/plugins/ssh-agent/1.22/ssh-agent.hpi
> chore(deps): downgrade ssh-agent to 1.21 from 1.22

- Jenkinsfile_k8s
We have a lot of builds on infra.ci that seems stuck (most of the time the pod agent cannot be reached after a controller restart, because the pod had been stopped and removed).
While still not confident on the root cause, adding a circuit breaker and a timeout is not a bad practice at all.
Hence this PR add the following circuit breaker to the pipeline:
- The docker build is timeouted to 10 min.
- Most of the builds are taking 4 to 6 min, and tests are 2 to 4 minutes.
- Timeout means either a network isssue, or a slow agent when executing the tests
- The pipeline is retried 3 times, to ensure network transient issues or pod performances are not blocking us. But after 3 retries, it is no use to retry.
> chore: set a 30min timeout (3 retries of 10 minutes)

- plugins.txt
CloudBees Health Advisor report mentioned this plugin to be "no longer distributed",
as we were explicitly installing a "not recommended" version.
- https://support.cloudbees.com/hc/en-us/articles/4402425444635
- https://github.com/jenkins-infra/update-center2/blob/master/resources/artifact-ignores.properties#L560
This commit removes the explicit from plugins.txt and delegates
github-api installation to transitive dependencies.
> fix: remove github-api plugin from explicit dependencies

- plugins.txt
`workflow-cps-global-lib` has been deprecated in favor of `pipeline-groovy-lib`
Ref: https://github.com/jenkins-infra/helpdesk/issues/3011
> chore(plugins): migrate from `workflow-cps-global-lib` to `pipeline-groovy-lib`

- plugins.txt
Though not yet https://github.com/jenkinsci/kubernetes-plugin/pull/1190: https://github.com/jenkins-infra/docker-jenkins-weekly/pull/512#discussion_r917130359
See https://github.com/jenkinsci/bom/pull/1252
Will include https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/249 if and when released.
@dduportal
> [JENKINS-49707] Use released versions of some plugins

- plugins.txt
Adding the build trigger badge on infra.ci, already present on ci.jenkins.io
It will help us see at a glance replayed builds.
https://plugins.jenkins.io/buildtriggerbadge/
> This plugin displays icon(s) representing the cause(s) of a build directly in the build history. It lets you quickly know which cause triggered a build.Without this plugin, you may sometimes wonder what triggered a particular build shown in the build history.
> To know it, you have to open each link separately, which can be cumbersome.
> feat: add buildtriggerbadge plugin

- .github/workflows/plugins-update.yaml
isn't the outputs missing ?
as per example here : https://github.com/jenkins-infra/captain-hook/blob/f68d4afb0fe03f60da896c7258685d08a6402dae/.github/workflows/pr.yaml
and https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
> fix (gha): should correct ouput

- plugins.txt
Following up #512 and countermanding #532 if you are willing to run these prior to release @dduportal. Picks up https://github.com/jenkinsci/workflow-api-plugin/pull/256 + https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180. Briefly, this would make it possible for `retry` blocks to work even if the agent outage was detected during a controller restart, as might occur for example during cluster updates (draining node pools, that sort of thing).
> [JENKINS-49707] Pick up proposed final changes

- .github/workflows/latest-weekly.yaml
- .github/workflows/plugins-update.yaml
Reverts jenkins-infra/docker-jenkins-weekly#637
<details>
<summary>Error log:</summary>
```console
Run echo "stdout=$(./bin/update-plugins.sh)\n" >> $GITHUB_OUTPUT
++ dirname ./bin/update-plugins.sh
+ cd ./bin
+ echo 'Updating plugins'
++ curl -s https://api.github.com/repos/jenkinsci/plugin-installation-manager-tool/releases/latest
++ jq -r '.assets[] | select(.content_type=="application/java-archive").browser_download_url'
+ PM_CLI_DOWNLOAD_URL=https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.9/jenkins-plugin-manager-2.12.9.jar
++ mktemp -d
+ TMP_DIR=/tmp/tmp.BU2V62vhIU
+ wget --no-verbose https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.9/jenkins-plugin-manager-2.12.9.jar -O …
```
> Revert "Address `set-output` deprecation"

- .github/workflows/latest-weekly.yaml
- .github/workflows/release-drafter.yml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402
> chore: pin GitHub actions with their SHA-1 instead of their version number (#1082

- bin/update-plugins.sh
This PR allows to keep comments in plugins.txt (for example when we want to [try an incremental plugin version](https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1125)) by putting modifications in a patch, modifying this patch to keep comments, then applying this patch on the initial plugins.txt content.
> feat(gha): keep comments in plugins.txt

- plugins.txt
The plugin enhances the header with Jenkins symbols, user themes and custom css. I thought it would be a nice addition to add it to our show-off instance weekly.ci
> Install customizable-header plugin on weekly.ci

- plugins.txt
as per https://github.com/jenkins-infra/helpdesk/issues/3597
> chore (plugins): remove popper2-api

- bin/update-plugins.sh
Since https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.13, the publication method changed with a direct consequence: the application type in the GitHub Releases API is now `application/x-java-archive` instead of `application/java-archive`
> hotfix(update-plugins.sh) correct the `jq` request to use new content type for getting plugin manager CLI

- Dockerfile
Fixup of #1379 
Copying to $JENKINS_HOME worked for me locally with Docker but it didn't work (as expected) with runc/containerd as it's a data volume. 
Ref: https://github.com/jenkinsci/docker#installing-more-tools
> fix: correct location for user content

- plugins.txt
This PR removes this plugin.
Revert:
- #1423
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3862
> chore: remove `plugin-agent-build-history` plugin

- plugins.txt
as per https://github.com/jenkins-infra/helpdesk/issues/3880
as Cobertura had dependency on old `code-coverage-api` and is not used anymore, let's remove it.
> feat(plugins): removing Cobertura plugin

- plugins.txt
Ref. jenkins-infra/helpdesk#3880 (comment)
- This plugin has not been updated since 4 years (ref. https://plugins.jenkins.io/github-autostatus/dependencies/)
- It should be replaced by github-checks (https://plugins.jenkins.io/github-checks/)
> feat(plugins) remove github-autostatus as unneeded

- .github/workflows/plugins-update.yaml
- Jenkinsfile_k8s
- bin/select-target-from-modified-files.sh
- bin/update-plugins.sh
This PR allows to build:
- Only infra.ci.jenkins.io image variant if only plugins-infra.ci.jenkins.io.txt if modified (with the update-plugins GHA)
- Only weekly.ci.jenkins.io image variant if only plugins-weekly.ci.jenkins.io.txt if modified (with the update-plugins GHA)
- Both image variants there is more than one of these files among a list of files requiring a build
- No image variant build if none of the modified file(s) is requiring a build
Tested with replays in #1470 by alternating the modified files in that PR:
- Success with only `infra-ci` target, only variant built:
- Modified files: README.md, plugins-infra.ci.jenkins.io.txt
- https://infra.ci.jenkins.io/job/docker-jobs/job/docker-jenkins-weekly/job/PR-1470/48/
- Corresponding commit: …
> feat: select target to build depending on the requirement of the modified files

- .github/workflows/release-drafter.yml
- Jenkinsfile_k8s
This PR:
- [`Jenkinsfile_k8s`] Removes a non-existing parameter (`useContainer`)  - (it does not make sense to build container in container and see https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildDockerAndPublishImage.groovy for reference)
- [`Jenkinsfile_k8s`] Removes a parameter which value is already the default one
- [GHA] Use the proper name for the Release Drafter workflow (CD is unrelated and scary in the context of a PR check: most probably a copy and paste from a plugin)
> chore(Jenkinsfile) cleanup buildDockerAndPublishImage call

- plugins-weekly.ci.jenkins.io.txt
This PR updates the pipeline-graph-view plugin to its last version on weekly.ci.jenkins.io variant.
This should result in the publication of only the `-weeklyci` tag for this version, to try out https://github.com/jenkins-infra/kubernetes-management/pull/4867/
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3887#issuecomment-1894297763
> test: update only pipeline-graph-view in weekly.ci plugins to get a single image variant

- .github/workflows/latest-weekly.yaml
- .github/workflows/plugins-update.yaml
> chore(GHA): address `set-output` deprecation

- .github/workflows/latest-weekly.yaml
This PR does the same as #1569 for the latest-weekly GitHub Action.
<details><summary>Output:</summary>
</details>
> chore(GHA/latest-weekly): proper pull request body

- .github/workflows/latest-weekly.yaml
- .github/workflows/plugins-update.yaml
This PR avoid failing GitHub Actions updating plugins if there isn't any new plugin version.
> fix(GHA): don't fail if there is no plugin update

- plugins-infra.ci.jenkins.io.txt
- plugins-weekly.ci.jenkins.io.txt
as per https://github.com/jenkins-infra/helpdesk/issues/4080
as per https://github.com/jenkins-infra/helpdesk/issues/4080#issuecomment-2095863202 depends on https://github.com/jenkins-infra/kubernetes-management/pull/5209
removing the datadog plugin as not used and prone to crashing the build xml files
> feat(weekly.ci/infra.ci): remove datadog plugin

- Jenkinsfile_k8s
related to https://github.com/jenkins-infra/helpdesk/issues/4171
This PR fixes the version scheme used for the new image (after splitting) by adding metadata suffix and fixing the existing tags and commit messages.
- Main change is cherry-picking (from the repository history) the technique used to tune the `jx-release-version` output to add the metadata (the Jenkins core version in our case) as version scheme suffix
- Also, the change in #1640 showed the new version (as per the default `jx-release-version` command) would be `2.0.0`.
- But the merge of the PR created a changed commit message which demises this hypothesis, resulting in a `1.49.2` version instead as the `BREAKING CHANGE` footer was not the last line (while `jx-release-version`  expects it).
- I've removed the generated …
> chore(Jenkins) add Jenkins Core version back in the metadatas

- Dockerfile
- bin/update-plugins.sh
Fix the invalid UC plugins infos URL as per https://github.com/jenkins-infra/docker-jenkins-lts/pull/900#pullrequestreview-2232610072.
Many thanks @timja !
> chore: use correct UC plugins infos URL - fixup of #1660

- bin/update-plugins.sh
Same as:
- https://github.com/jenkins-infra/docker-jenkins-lts/pull/967
Ref:
- https://github.com/jenkins-infra/docker-jenkins-lts/issues/865
> chore: verify checksum of plugin installation manager tool before executing
