Jenkinsfile_k8s

chore: implement a CI circuitbreaker - JENKINS-51454

---

Jenkinsfile_k8s

chore: increase pipeline timeout as network is slow

---

Jenkinsfile_k8s

chore: bump the jx-next-version to 2.4.13

---

.github/workflows/update.yaml

No more @garethjevans committer details 😄 
https://github.com/jenkins-infra/docker-jenkins-weekly/commits/main

Set committer details

---

plugins.txt

Reverts jenkins-infra/docker-jenkins-weekly#346

Revert "Add http request plugin for infra"

---

plugins.txt

moar plugins

---

Dockerfile
Jenkinsfile_k8s
plugins.txt

https://github.com/jenkins-infra/helpdesk/issues/2803

Debug: pin Core to 2.335

---

plugins.txt

Part of https://github.com/jenkins-infra/helpdesk/issues/2855

feat: add design-library for weekly.ci.jenkins.io

---

.github/workflows/update.yaml

Also use our github app email (So Gareth doesn't appear as author anymore?)

chore(gha-updatecli-plugins): view the diff directly in the PR body

---

plugins.txt

https://github.com/jenkins-infra/pipeline-library/pull/405#issuecomment-1154343159
Picks up
* https://github.com/jenkinsci/workflow-api-plugin/pull/217
* https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/231
* https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/203
* https://github.com/jenkinsci/kubernetes-plugin/pull/1190
See https://github.com/jenkinsci/plugin-installation-manager-tool#plugin-input-format

[JENKINS-49707] Experimental plugin updates for `node`-block retry

---

plugins.txt

Ref. https://github.com/jenkins-infra/helpdesk/issues/3013

Remove plugin embeddable-build-status

---

plugins.txt

https://github.com/jenkins-infra/helpdesk/issues/2984#issuecomment-1183305821 picking up https://github.com/jenkinsci/kubernetes-plugin/pull/1190

`kubernetes` released as `3663.v1c1e0ec5b_650`

---

Dockerfile
plugins.txt

debug: rollback core to 2.358 weekly

---

.github/workflows/latest-weekly.yaml

should match the workflow of the docker weekly repo and avoid the line feed/return back and force

fix(workflow): change plugins update check process

---

.github/workflows/plugins-update.yaml

renaming the file for clarity and try to remove tests from the body variable

chore(github workflow): rename and correction

---

plugins.txt

https://github.com/jenkinsci/pipeline-graph-view-plugin/
Ref: https://groups.google.com/g/jenkinsci-dev/c/TCnhBl8evQE

feat: add pipeline-graph-view plugin

---

plugins.txt

[JENKINS-49707] Pick up final releases

---

Dockerfile
plugins.txt

manually generated PR to update jenkins

feat(jenkins): manually update jenkins to 2.387 and the plugins

---

plugins.txt

Ref. https://github.com/jenkins-infra/update-center2/pull/679

cleanup: remove deprecated jquery plugin

---

plugins.txt

Ref. https://github.com/jenkins-infra/helpdesk/issues/3374

fix(plugins) Remove ace-editor bundle plugin

---

plugins.txt

https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/299#issuecomment-1461947698

Pick up jenkinsci/workflow-durable-task-step-plugin#299

---

bin/update-plugins.sh

fix(update-plugin.sh): if the patch is corrupted log its content and exit (#1134

---

bin/update-plugins.sh

Fixup of #1131 & #1134 
Ref: #1133

fix(update-plugins.sh): don't try to apply the patch if there is no plugin updated

---

plugins.txt

Ref: https://github.com/jenkins-infra/helpdesk/issues/2844

cleanup: remove `prometheus` plugin

---

plugins.txt

chore: restore comment in plugins.txt

---

plugins.txt

as per https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/299
remove incremental

chore(plugin workflow-durable-task-step): remove incremental as PR #299 is merged)

---

cst.yml
plugins.txt

as not used anymore
as per https://github.com/jenkins-infra/helpdesk/issues/3471

feat(plugins): remove ec2 plugin

---

Jenkinsfile_k8s

Related (long term) to https://github.com/jenkins-infra/helpdesk/issues/3619

feat: add arm64 image

---

plugins-weekly.ci.jenkins.io.txt

Thanks to Hervé's great work, we can remove a few more plugins we don't use on weekly.ci.

Remove unused plugins from weekly.ci

---

plugins-infra.ci.jenkins.io.txt

Ref. https://github.com/jenkins-infra/helpdesk/issues/2778
Blocks https://github.com/jenkins-infra/kubernetes-management/pull/5015

feat(infra.ci) add the github-scm-trait-notification-context plugin

---

.github/workflows/plugins-update.yaml

This PR fixes the body created by the plugins-update GHA, listing changes and new plugin release links.

chore(GHA/plugins-update): proper pull request body

---

.github/workflows/plugins-update.yaml
bin/update-plugins.sh

hotfix(GHA): no git diff in udpate-plugins script

---

.github/workflows/plugins-update.yaml

to avoid a PR when no changes detected.

fixup(weekly): wrong test for changes in action updateplugins

---

plugins.txt

This controller is effectively a demonstration of SIG UX work, so let's theme it up

Add theme plugins
